source 'https://rubygems.org'

gem 'xcpretty'
gem 'i18n'
gem 'fui'
gem 'obcd'
gem 'cocoapods'
gem 'shenzhen'
gem 'deliver'
gem 'slather', '~> 1.7.1'
gem 'codes'
gem 'rake'
gem 'cocoapods-keys', :git => 'https://github.com/jhersh/cocoapods-keys.git', :branch => 'keys-paths'
gem 'pygmentize'
