source 'https://rubygems.org'

gem 'xcpretty'
gem 'i18n'
gem 'fui'
gem 'obcd'
gem 'cocoapods', '0.38.0.beta.2'
gem 'shenzhen'
gem 'deliver'
gem 'codes'
gem 'rake'
gem 'cocoapods-keys'
gem 'pygmentize'
